export {
  CUSTOM_TEMPLATE_VALUE as HOME_KIND_OTHER,
  ROOM_TEMPLATE_OPTIONS as ROOM_KIND_SUGGESTIONS,
  STORAGE_LOCATION_TEMPLATE_OPTIONS as STORAGE_LOCATION_KIND_SUGGESTIONS,
} from "./home-template-options";
