// Generated by scripts/generate-phosphor-icon-registry.mjs. Do not edit manually.
import type { ComponentType } from "react";
export type PhosphorIconComponent = ComponentType<{ "aria-hidden"?: boolean | "true"; className?: string; size?: number; weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone" }>;
export type PhosphorIconGroupModule = { ICONS: Record<string, PhosphorIconComponent> };
export const PHOSPHOR_ICON_GROUP_LOADERS: Record<number, () => Promise<PhosphorIconGroupModule>> = {
  0: () => import("./phosphor-icon-groups/group-000"),
  1: () => import("./phosphor-icon-groups/group-001"),
  2: () => import("./phosphor-icon-groups/group-002"),
  3: () => import("./phosphor-icon-groups/group-003"),
  4: () => import("./phosphor-icon-groups/group-004"),
  5: () => import("./phosphor-icon-groups/group-005"),
  6: () => import("./phosphor-icon-groups/group-006"),
  7: () => import("./phosphor-icon-groups/group-007"),
  8: () => import("./phosphor-icon-groups/group-008"),
  9: () => import("./phosphor-icon-groups/group-009"),
  10: () => import("./phosphor-icon-groups/group-010"),
  11: () => import("./phosphor-icon-groups/group-011"),
  12: () => import("./phosphor-icon-groups/group-012"),
  13: () => import("./phosphor-icon-groups/group-013"),
  14: () => import("./phosphor-icon-groups/group-014"),
  15: () => import("./phosphor-icon-groups/group-015"),
};
